language: ruby
rvm:
- 2.6.5
cache: bundler
notifications:
  slack:
    secure: rbqShUrMX7Qxy74l+TkJefdxSCFdD9o6JyDEiZqDz49zXU0yYiS5uWB2nOfMOfGP3LomROkqLlL+huiADf4StOfrqSyEv4zfA7H1jVq+/JDWmS95b/w00C/pbCyIiku9QuCraz8d72U3bK/ZchyO5GCmr2KLuB/xneBMShC8aF7SVQKctSOCv+xUoNsDYGVwPQMS262WK1ytyjO4YHbe+h4i1v2+2Vrlxl/3HXS8G/JIDcWxLdCjbnIfNUYhPZL1CgXIz0eWmu6QNcLGI/pykjnSDCejgD6SZTn+DLC1j5EsAnYwTIBSBXHycnTHb+CCF2wzxviMGMAYrRyWWGwmumV+A3OPmEWWijyXT9tb0kh6NMVgdbLyrmGODQzh/bQ1iFbj83eWHJF5AuTk9zfFnwqyOMf7tuGirG0EmAfxeWpK/TujWtwgbfUpABJE6yE6ZJFG17JG006eG/sXkkVsV6uMuSFNHuxLBa27c8X9VHyfo1StqOpgnxlb8pJO7tZEzU9jh+ikvzZvtcNZUfJ6bkBSN0VUYn7niFL8j+NSEYS1W5okC3ewWbEOn8DWaqF5f13wOq32+uNAEWA0y2aXBvlCWNf3Zt43QkfYu6stu/4twxcaQf9KnaJ0Fl6Na9ZQ6iUK+mqKnZABnoVkMsXY2rd0pwve2GD7dB7/d1S7AdU=
